# route: 
#   group_by: ['alertname']
#   group_wait: 5s
#   group_interval: 5s
#   repeat_interval: 5s
#   receiver: 'gmail-notifications'

# receivers:
# - name: 'gmail-notifications'
#   email_configs:
#     - to: abcdefgh@mail.com
#       from: abcdefgh@mail.com
#       smarthost: smtp.gmail.com:587
#       auth_username: abcdefgh@mail.com
#       auth_identity: abcdefgh@mail.com
#       auth_password: abcdefgh
#       send_resolved: true

# replace the flock api webhook url with yours

global:
  resolve_timeout: 5m
  slack_api_url: 'https://api.flock.com/hooks/sendMessage/blah-bleh-bluh-blah'
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1m
  receiver: 'Prometheus-Session'
  routes:
  - match:
      severity: critical
    receiver: 'Prometheus-Session'
  - match:
      severity: warning
    receiver: 'Prometheus-Session'

receivers:
  - name: 'Prometheus-Session'
    slack_configs:
    - send_resolved: true
      title: "{{ range .Alerts }}{{ .Annotations.description }} {{ end }}"
      text: "Nodes: {{ range .Alerts }}{{ .Labels.instance }} {{ end }} \nDescription: {{ .CommonAnnotations.description }} \nSummary: {{ .CommonAnnotations.summary }}"
#      title: "{{ range .Alerts }} \n {{ .Annotations.description }}\n {{ end }}\n"

# docker ps | grep redis_exporter | awk '{print $1}' | xargs docker kill
# sudo lsof -t -i tcp:3000 -s tcp:listen | sudo xargs kill
