version: '3'


services:
    alertmanager:
      image: prom/alertmanager:v0.14.0
      ports:
        - 9093:9093
      network_mode: 'host'
      command:
        - '--log.level=debug'
        - '--config.file=/etc/alertmanager/alertmanager_config.yml'
        - '--storage.path=/alertmanager'
      volumes:
        - ${PWD}/alertmanager:/etc/alertmanager/
        - ./alertmanager_data:/alertmanager

    redis:
      image: 'redis'
      ports:
          - 6379:6379
      network_mode: 'host'

    redis_exporter:
      image: oliver006/redis_exporter
      ports:
          - 9121:9121
      network_mode: 'host'

    prometheus:
      image: prom/prometheus:v2.20.1
      ports:
        - 9090:9090
      user: root
      network_mode: 'host'
      volumes:
        - ./prometheus_data:/prometheus
        - ./prometheus/:/etc/prometheus/
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    grafana:
      image: grafana/grafana
      ports:
        - 3000:3000
      user: root
      network_mode: 'host'
      environment:
        - GF_SMTP_ENABLED=true
        - GF_SMTP_HOST=smtp.gmail.com:587
        - GF_SMTP_USER=abcdefgh@mail.com  
        - GF_SMTP_PASSWORD=abcdefgh
        - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
        - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
        - GF_USERS_ALLOW_SIGN_UP=false
      volumes:
        - ./grafana/grafana_data:/var/lib/grafana
        - ./grafana/datasources:/etc/grafana/datasources
        - ./grafana/dashboards:/etc/grafana/dashboards
        - ./grafana/setup.sh:/setup.sh
      entrypoint: /setup.sh


