{
 "title": "Redis Dashboard",
 "description": "Redis Dashboard",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds[$__interval]))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(redis_connected_clients)" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * sum(redis_memory_used_bytes)  / sum(redis_memory_max_bytes )"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total[1m])"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Running Instances",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "up", "legendFormat": "{{ instance}} : {{ job }}" }
   ]
  },
  {
   "title": "Redis Cluster Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "redis_cluster_size", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Total Items in DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "sum (redis_db_keys)" }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys) - sum (redis_db_keys_expiring) ",
     "legendFormat": "not expiring"
    },
    { "expr": "sum (redis_db_keys_expiring) ", "legendFormat": "expiring" }
   ]
  },
  {
   "title": "CPU usage by system in seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_cpu_sys_seconds_total[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Usage by user in seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_cpu_user_seconds_total[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Cluster Slots Assigned",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "redis_cluster_slots_assigned", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Pings sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_cluster_stats_messages_ping_sent",
     "legendFormat": " {{ instance }}"
    }
   ]
  },
  {
   "title": "Pings received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_cluster_stats_messages_ping_received",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Cluster known Nodes",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "redis_cluster_known_nodes", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Cluster slots Failed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum (redis_cluster_slots_fail)", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Cluster State",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "min (redis_cluster_state)", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Total Exporter Scrapes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "redis_exporter_scrapes_total{instance=\"localhost:9121\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Cluster Messages Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_cluster_messages_received_total",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total[5m])",
     "legendFormat": "{{ input }}"
    },
    {
     "expr": "rate(redis_net_output_bytes_total[5m])",
     "legendFormat": "{{ output }}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "redis_memory_used_bytes", "legendFormat": "used" },
    { "expr": "redis_memory_max_bytes ", "legendFormat": "max" }
   ]
  },
  {
   "title": "Redis Allocator Resident bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "redis_allocator_resident_bytes", "legendFormat": "{{ instance }}: {{ job }}" }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total[5m])) by (instance)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total[5m])) by (instance)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Redis Allocator rss bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "redis_allocator_rss_bytes", "legendFormat": "{{ instance }}: {{ job }}" }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total[1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  }
 ]
}